=== huaweihulk/zhanwai/zhanwai/src/main/resources/downloadparam.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/downloadparam"
	xmlns:tns="http://www.example.org/downloadparam" elementFormDefault="qualified">
	<simpleType name="requestmethod">
		<restriction base="string">
			<enumeration value="GET"></enumeration>
			<enumeration value="POST"></enumeration>
		</restriction>
	</simpleType>
	<simpleType name="urltype">
		<restriction base="string">
			<enumeration value="category"></enumeration>
			<enumeration value="productlist"></enumeration>
			<enumeration value="productdetail"></enumeration>
		</restriction>
	</simpleType>
	<element name="client">
		<complexType>
			<sequence>
				<element name="url" type="string" />
				<element name="method" type="tns:requestmethod" />
				<element name="user_agent" type="string"
					default="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0" />
				<element name="referer" type="string" />
				<element name="paserclass" type="string"></element>
				<element name="cookie" type="string" />
				<element name="urltype" type="tns:urltype" />
			</sequence>
		</complexType>
	</element>
	<element name="clients">
		<complexType>
			<sequence>
				<element ref="tns:client" />
			</sequence>
		</complexType>
	</element>

</schema>

=== huaweihulk/zhanwai/zhanwai/src/main/resources/downloadClients.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns:xsi="http://www.w3.org/2001/XMLSchema"
	xsi:noNamespaceSchemaLocation="downloadparam.xsd">
<!--  	<client>
		<url>http://www.huipinzhe.com/</url>
		<referer>http://www.huipinzhe.com/</referer>
		<method>GET</method>
		<urltype>category</urltype>
		<user_agent>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0</user_agent>
		<cookie></cookie>
		<paserclass>HuiPinZheCategoryParse</paserclass>
	</client>  -->
 	<client>
		<url>http://www.zhe800.com/</url>
		<referer>http://www.zhe800.com</referer>
		<method>GET</method>
		<urltype>category</urltype>
		<user_agent>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0</user_agent>
		<cookie></cookie>
		<paserclass>ZheBaBaiCategoryParse</paserclass>
	</client> 
</clients>
